name = "uptimeflare_worker"
main = "src/index.ts"
compatibility_date = "2023-11-08"

[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "UPTIMEFLARE_STATE"
id = "76b800d860fe45a6a650cda9ff1ce284"
